### ISSUE TITLE
add a parameter to "yes_it_shipped" assertion to overwrite the default server

### ISSUE THREAD

**Issue by jordimassaguerpla** [cornelius/yes_ship_it#27]
Even thought it may be nice to have a centralized "yes_it_shipped" server to see all projects that use it, it is convenient to be able to overwrite that default by adding a parameter.

Use cases:

- testing yes_ship_it
- private projects with its own "yes_it_shipped" hosting

**Comment by cornelius** [comment]
This makes sense. Your patch looks good. Would you mind creating a test and submit it as a pull request?
